#!/bin/bash
#This is for redhat 7.4
yum install -y rdma-core
yum install -y opensm-libs
yum install -y libibmad
yum install -y libibcm
yum install -y libibumad
yum install -y rdma-core-devel
yum install -y tcsh
yum install -y libibverbs
yum install -y ibacm
yum install -y atlas
yum install -y bc
yum install -y expect
yum install -y tcl
yum install -y qperf
yum install -y perftest
yum install -y infinipath-psm
yum install -y libgfortran
yum install -y gcc-gfortran
yum install -y libquadmath
yum install -y librdmacm
yum install -y libstdc++-devel
yum install -y papi
yum install -y elfutils-libelf-devel
yum install -y sysfsutils
yum install -y kernel-devel
yum install -y rpm-build
yum install -y redhat-rpm-config
yum install -y readline-devel
yum install -y ncurses-devel
