#This is for redhat 7.4 RPMs
yum remove -y rdma-core
yum remove -y opensm-libs
yum remove -y libibmad
yum remove -y libibcm
yum remove -y libibumad
yum remove -y rdma-core-devel
yum remove -y tcsh
yum remove -y libibverbs
yum remove -y ibacm
yum remove -y atlas
yum remove -y bc
yum remove -y expect
yum remove -y tcl
yum remove -y qperf
yum remove -y perftest
yum remove -y infinipath-psm
yum remove -y libgfortran
yum remove -y gcc-gfortran
yum remove -y libquadmath
yum remove -y librdmacm
yum remove -y libstdc++-devel
yum remove -y papi
yum remove -y elfutils-libelf-devel
yum remove -y sysfsutils
yum remove -y kernel-devel
yum remove -y rpm-build
yum remove -y redhat-rpm-config
yum remove -y readline-devel
yum remove -y ncurses-devel
